import { useState } from 'react';
import { pickFile, request, thumbnailUrl } from './api';
import { Icon } from './icons';
import { timecode, type Command } from './App';
import type { Job, Match, Project } from './types';

const initialMatch: Match = { team_a: 'Team A', team_b: 'Team B', players: ['A1', 'A2', 'B1', 'B2'].map(player_id => ({ player_id, team: player_id[0], name: `Player ${player_id}` })), starting_server: 'A1', starting_receiver: 'B1', initial_score_a: 0, initial_score_b: 0, target_score: 21 };
export function Setup({ project, command, update, onError, onBack }: { project: Project | null; command: Command; update: (p: Project) => void; onError: (e: unknown) => void; onBack: () => void }) {
  const [step, setStep] = useState(project ? 1 : 0);
  const [path, setPath] = useState(project?.video_path ?? '');
  const [title, setTitle] = useState(project?.title ?? '');
  const [match, setMatch] = useState<Match>(project?.match_settings ?? initialMatch);
  const [mode, setMode] = useState<'automatic' | 'manual'>(project?.mode === 'manual' ? 'manual' : 'automatic');
  const [saving, setSaving] = useState(false);
  const names = Object.fromEntries(match.players.map(p => [p.player_id, p.name]));
  const change = (values: Partial<Match>) => setMatch(old => ({ ...old, ...values }));
  const browse = async () => { try { const value = await pickFile('video'); if (value) setPath(value); } catch (e) { onError(e); } };
  const next = async () => {
    if (step === 0) {
      if (!path.trim()) return;
      setSaving(true);
      try { update(await request<Project>('/projects', { video_path: path, title: title.trim() || undefined })); } catch (e) { onError(e); } finally { setSaving(false); }
    } else if (step === 3) {
      setSaving(true); try { await command('setup', { match_settings: match, mode, title: title.trim() || undefined }); } finally { setSaving(false); }
    } else setStep(step + 1);
  };
  return <main className="setup-page"><aside className="setup-aside"><div className="eyebrow">LET’S SET THE STAGE</div><h1>One match.<br/>Every moment.</h1><p>A few details now make your score,<br/>stats, and replay work together.</p><ol>{['Your recording', 'Teams & players', 'First serve', 'Your editing style'].map((label, index) => <li key={label} className={index === step ? 'active' : index < step ? 'complete' : ''}><span>{index < step ? <Icon name="check" size={15}/> : index + 1}</span>{label}</li>)}</ol><div className="aside-note"><Icon name="folder"/><span>Saved locally, as you go.<br/>Your original recording stays intact.</span></div></aside>
    <section className="setup-content"><div className="eyebrow">STEP {step + 1} OF 4</div>
      {step === 0 && <><h2>Bring your game.</h2><p>Choose the full recording from your computer.</p><button className="file-drop" onClick={() => void browse()}><span className="file-icon"><Icon name="video" size={32}/></span><strong>Select a recording</strong><span>MP4, MOV, MKV, and other FFmpeg formats</span><span className="button">Browse files</span></button><label>Recording path<input autoFocus value={path} onChange={e => setPath(e.target.value)} placeholder="/path/to/your/game.mov"/></label><label>Match title <span className="optional">optional</span><input value={title} onChange={e => setTitle(e.target.value)} placeholder="Saturday doubles · Court 2"/></label><p className="helper">Use an absolute file path if your system file picker is unavailable.</p></>}
      {step === 1 && <><h2>Who’s on the court?</h2><p>Two teams. Four players. Make it yours.</p><label>Match title<input value={title} onChange={e => setTitle(e.target.value)} placeholder="Give this game a name"/></label><div className="team-setup-grid">{['A', 'B'].map(team => <div className={`team-form team-${team.toLowerCase()}`} key={team}><span className="team-label">TEAM {team}</span><label>Team name<input value={team === 'A' ? match.team_a : match.team_b} onChange={e => change({ [team === 'A' ? 'team_a' : 'team_b']: e.target.value })}/></label>{match.players.filter(p => p.team === team).map((p, i) => <label key={p.player_id}>Player {i + 1}<input value={p.name} onChange={e => change({ players: match.players.map(player => player.player_id === p.player_id ? { ...player, name: e.target.value } : player) })} maxLength={80}/></label>)}</div>)}</div><details className="match-options"><summary>Match options <span>Starting score & points to win</span></summary><div className="row"><label>{match.team_a} score<input type="number" min="0" max="999" value={match.initial_score_a} onChange={e => change({ initial_score_a: Number(e.target.value) })}/></label><label>{match.team_b} score<input type="number" min="0" max="999" value={match.initial_score_b} onChange={e => change({ initial_score_b: Number(e.target.value) })}/></label><label>Points to win<input type="number" min="2" max="99" value={match.target_score} onChange={e => change({ target_score: Number(e.target.value) })}/></label></div>{match.initial_score_a + match.initial_score_b > 0 && <p className="warning-text">For a partial recording, select the server and receiver at its first point. Earlier player stats are unknown and full-match RPR is unavailable. The serving cycle starts from this pair.</p>}</details></>}
      {step === 2 && <><h2>Who serves first?</h2><p>Choose a server, then the player receiving across the net.</p><div className="role-label">1. STARTING SERVER</div><div className="player-picker">{match.players.map(p => <button key={p.player_id} className={`player-button ${p.team === 'A' ? 'team-a' : 'team-b'} ${match.starting_server === p.player_id ? 'selected' : ''}`} onClick={() => change({ starting_server: p.player_id, starting_receiver: p.team === match.starting_receiver[0] ? match.players.find(v => v.team !== p.team)!.player_id : match.starting_receiver })}>{p.name}<small>{p.team === 'A' ? match.team_a : match.team_b}</small></button>)}</div><div className="role-label">2. STARTING RECEIVER</div><div className="player-picker">{match.players.filter(p => p.team !== match.starting_server[0]).map(p => <button key={p.player_id} className={`player-button team-${p.team.toLowerCase()} ${match.starting_receiver === p.player_id ? 'selected' : ''}`} onClick={() => change({ starting_receiver: p.player_id })}>{p.name}</button>)}</div><div className="position-diagram"><span className="position-player server">{names[match.starting_server]}<small>SERVER</small></span><div className="position-net"><span/></div><span className="position-player receiver">{names[match.starting_receiver]}<small>RECEIVER</small></span></div><p className="helper">Equal serving: the opening server serves once, then players take two serves. Python updates the order as you classify each point.</p></>}
      {step === 3 && <><h2>How do you want to edit?</h2><p>Pick a starting point. You can adjust every clip afterward.</p><button className={`mode-card ${mode === 'automatic' ? 'selected' : ''}`} onClick={() => setMode('automatic')}><span className="mode-symbol">✦</span><span><strong>Find rallies automatically</strong><span>Mark the court, let the detector suggest cuts,<br/>then review what happened.</span></span><span className="radio-dot"/></button><button className={`mode-card ${mode === 'manual' ? 'selected' : ''}`} onClick={() => setMode('manual')}><Icon name="video" size={28}/><span><strong>Mark clips myself</strong><span>Go straight to the recording and mark<br/>the start and end of each rally.</span></span><span className="radio-dot"/></button><div className="setup-summary"><span>{match.team_a} <b>vs</b> {match.team_b}</span><small>{names[match.starting_server]} serves to {names[match.starting_receiver]} · First to {match.target_score}</small></div></>}
      <div className="setup-actions"><button className="button subtle" onClick={() => step > (project ? 1 : 0) ? setStep(step - 1) : onBack()}><Icon name="back"/>Back</button><button className="button primary" disabled={saving || step === 0 && !path.trim()} onClick={() => void next()}>{saving ? 'Saving…' : step === 3 ? mode === 'manual' ? 'Start editing' : 'Set up the court' : 'Continue'}<Icon name="arrow"/></button></div>
    </section></main>;
}

export function JobProgress({ job, onError }: { job: Job; onError: (e: unknown) => void }) {
  const cancel = async () => { try { await request(`/jobs/${job.id}/cancel`, {}); } catch (e) { onError(e); } };
  return <div className="job-progress" aria-live="polite"><div className="row"><strong>{job.message || (job.kind === 'detection' ? 'Finding rallies…' : 'Rendering your video…')}</strong><span>{Math.round(job.progress)}%</span></div><progress max={100} value={job.progress}/><div className="row"><span className="helper">{job.status === 'cancelled' ? 'Cancelled. Your project is saved.' : job.status === 'failed' ? job.error : job.status === 'succeeded' ? 'Complete' : 'You can cancel safely at any time.'}</span>{['queued', 'running'].includes(job.status) && <button className="button small" onClick={() => void cancel()}>Cancel</button>}</div></div>;
}

export function FindClips({ project, command, job, onJob, onError, busy }: { project: Project; command: Command; job: Job | null; onJob: (j: Job) => void; onError: (e: unknown) => void; busy: boolean }) {
  const [step, setStep] = useState(0);
  const [frame, setFrame] = useState(Math.min(project.video_duration / 3, 30));
  const [roi, setRoi] = useState<number[] | null>(project.roi ?? null);
  const [net, setNet] = useState<number[] | null>(project.court_context?.net ?? null);
  const [zones, setZones] = useState<number[][][]>(project.court_context?.serving_zones ?? []);
  const [draft, setDraft] = useState<number[][]>([]);
  const [origin, setOrigin] = useState<number[] | null>(null);
  const [settings, setSettings] = useState<Record<string, unknown>>(project.settings);
  const activeJob = job?.kind === 'detection' ? job : null;
  const point = (event: React.PointerEvent<SVGSVGElement>) => { const rect = event.currentTarget.getBoundingClientRect(); return [Math.max(0, Math.min(1, (event.clientX - rect.left) / rect.width)), Math.max(0, Math.min(1, (event.clientY - rect.top) / rect.height))]; };
  const start = async () => {
    try {
      const saved = await command('court', { roi, court_context: { net, net_radius: .08, serving_zones: zones } });
      if (!saved) return;
      onJob(await request<Job>(`/projects/${project.project_id}/detect`, { expected_revision: saved.revision, settings }));
    } catch (e) { onError(e); }
  };
  const undo = () => { if (step === 0) setRoi(null); else if (step === 1) setNet(null); else if (draft.length) setDraft(draft.slice(0, -1)); else setZones(zones.slice(0, -1)); };
  return <main className="find-page"><div className="section-heading"><div><div className="eyebrow">FIND THE GOOD PARTS</div><h1>A little court context.<br/><span>A better first cut.</span></h1><p>{['Drag a rectangle around the playing area. Include room for the players to move.', 'Click the center of the net. This is an optional supporting cue.', 'Click three or more corners of a serving zone, then finish it. Add up to four zones.'][step]}</p></div><button className="button" disabled={busy} onClick={() => void command('stage', { stage: 'review' })}>Mark clips manually<Icon name="arrow"/></button></div>
    <div className="find-layout"><section className="court-workspace"><div className="court-steps">{['Playing area', 'Net position', 'Serving zones'].map((title, i) => <button disabled={busy} className={step === i ? 'active' : ''} key={title} onClick={() => { setStep(i); setDraft([]); }}><span>{i + 1}</span>{title}</button>)}</div><div className="court-frame"><img src={thumbnailUrl(project.project_id, frame, 1280)} alt="Source frame for marking the court"/><svg viewBox="0 0 1000 1000" preserveAspectRatio="none" role="application" aria-label="Court marking canvas" onPointerDown={e => { if (busy) return; const p = point(e); if (step === 0) { setOrigin(p); e.currentTarget.setPointerCapture(e.pointerId); } else if (step === 1) setNet(p); else if (draft.length < 12 && zones.length < 4) setDraft([...draft, p]); }} onPointerMove={e => { if (origin && step === 0) { const p = point(e); setRoi([Math.min(origin[0], p[0]), Math.min(origin[1], p[1]), Math.abs(origin[0] - p[0]), Math.abs(origin[1] - p[1])]); } }} onPointerUp={e => { if (origin) { const p = point(e); const value = [Math.min(origin[0], p[0]), Math.min(origin[1], p[1]), Math.abs(origin[0] - p[0]), Math.abs(origin[1] - p[1])]; setRoi(value[2] > .01 && value[3] > .01 ? value : null); setOrigin(null); } }}>
      {roi && <rect x={roi[0] * 1000} y={roi[1] * 1000} width={roi[2] * 1000} height={roi[3] * 1000} className="roi-shape"/>}{net && <><ellipse cx={net[0] * 1000} cy={net[1] * 1000} rx={35} ry={45} className="net-shape"/><path d={`M${net[0] * 1000 - 10} ${net[1] * 1000}h20m-10-15v30`} stroke="#e4ef9a" strokeWidth="3"/></>}{zones.map((zone, i) => <polygon key={i} points={zone.map(p => p.map(v => v * 1000).join(',')).join(' ')} className="zone-shape"/>)}{draft.length > 0 && <polyline points={draft.map(p => p.map(v => v * 1000).join(',')).join(' ')} className="zone-shape draft"/>}{draft.map((p, i) => <circle key={i} cx={p[0] * 1000} cy={p[1] * 1000} r="5" fill="#e4ef9a"/>)}</svg></div>
      <div className="frame-picker"><Icon name="video"/><input type="range" min="0" max={Math.max(0, project.video_duration - .05)} step="0.25" value={frame} disabled={busy} aria-label="Choose a representative frame" onChange={e => setFrame(Number(e.target.value))}/><span>{timecode(frame)}</span></div><div className="row court-actions"><button className="button small" disabled={busy} onClick={undo}><Icon name="undo"/>Undo drawing</button>{step === 2 && <button className="button small" disabled={busy || draft.length < 3} onClick={() => { setZones([...zones, draft]); setDraft([]); }}>Finish zone ({zones.length}/4)</button>}{step < 2 && <button className="button small" disabled={busy} onClick={() => setStep(step + 1)}>Continue<Icon name="arrow"/></button>}</div></section>
      <aside className="find-sidebar"><span className="mode-symbol">✦</span><h2>Ready when you are.</h2><p>The detector suggests rally boundaries. You’ll review the cuts and decide what happened.</p><ul className="court-checklist"><li><Icon name={roi ? 'check' : 'plus'}/>{roi ? 'Playing area selected' : 'Full frame playing area'}</li><li><Icon name={net ? 'check' : 'plus'}/>{net ? 'Net position marked' : 'Net position optional'}</li><li><Icon name={zones.length ? 'check' : 'plus'}/>{zones.length} serving zones</li></ul><button className="button primary wide" disabled={busy || draft.length > 0} onClick={() => void start()}>Find rallies<Icon name="arrow"/></button>{draft.length > 0 && <p className="helper">Finish or undo the zone before finding rallies.</p>}
        {project.rallies.length > 0 && <button className="button wide" disabled={busy} onClick={() => void command('stage', { stage: 'review' })}>Review {project.rallies.length} clips<Icon name="arrow"/></button>}{activeJob && <JobProgress job={activeJob} onError={onError}/>}
        <details><summary>Advanced settings</summary>{[['rally_threshold', 'Rally threshold', .1, .95, .01, .55], ['analysis_fps', 'Analysis FPS', 1, 30, 1, 8], ['min_rally_duration', 'Minimum rally (s)', .5, 15, .5, 1.5], ['pre_roll', 'Pre-roll (s)', 0, 5, .25, .75], ['post_roll', 'Post-roll (s)', 0, 5, .25, 1.25]].map(([key, label, min, max, increment, fallback]) => <label key={String(key)}>{label}<input type="number" min={Number(min)} max={Number(max)} step={Number(increment)} value={Number(settings[String(key)] ?? fallback)} disabled={busy} onChange={e => setSettings({ ...settings, [key]: Number(e.target.value) })}/></label>)}<label className="checkbox"><input type="checkbox" disabled={busy} checked={settings.player_tracking_enabled !== false} onChange={e => setSettings({ ...settings, player_tracking_enabled: e.target.checked })}/>Player tracking</label>{project.rallies.length > 0 && <p className="helper">Running detection again replaces the clip list. You can undo the result.</p>}<Diagnostics project={project}/></details>
      </aside></div></main>;
}

function Diagnostics({ project }: { project: Project }) {
  const signals = project.signals; const timestamps = signals?.timestamps ?? [];
  if (!timestamps.length) return <p className="helper">Diagnostic graphs appear after detection.</p>;
  const series = [['rally_scores', 'Rally score', '#dfed9e'], ['motion_scores', 'Motion', '#a9c6e9'], ['audio_scores', 'Audio', '#dbac91']];
  const stride = Math.max(1, Math.floor(timestamps.length / 500));
  return <details><summary>Diagnostic signals</summary><svg className="diagnostic-chart" viewBox="0 0 300 110" role="img" aria-label="Detector rally, motion, and audio signals across the source recording"><path d="M0 10H300M0 55H300M0 100H300" stroke="#46523a" strokeWidth=".5"/>{series.map(([key, , color]) => { const values = signals?.[key] ?? []; return <polyline key={key} points={timestamps.filter((_, i) => i % stride === 0).map((time, i) => `${time / project.video_duration * 300},${100 - Math.max(0, Math.min(1, values[i * stride] ?? 0)) * 90}`).join(' ')} fill="none" stroke={color} strokeWidth="1"/>; })}</svg><div className="diagnostic-legend">{series.map(([, label, color]) => <span key={label}><i style={{ background: color }}/>{label}</span>)}</div><p className="helper">0:00 to {timecode(project.video_duration)} · normalized detector signals</p></details>;
}
